version: "3"
services:
  frontend:
    build: front-end
    command: yarn start
    ports:
      - "9000:9000"
    volumes:
      - ./front-end:/front
      - frontend-deps:/front/node_modules
  backend:
    build: back-end
    command: yarn start
    ports:
      - "3000:3000"
    networks:
      - app
    links:
      # within backend container, now we can use the namesapce as hostname('database' instead of 'localhost')
      # e.g. mongoose.connect("mongodb://database:27017/feedbackly")
      - database
    volumes:
      - ./back-end:/back
      - backend-deps:/back/node_modules
    depends_on:
      - "database"
    command: ["./wait-for-it.sh", "database:27017", "--", "yarn", "start"]
    healthcheck:
      interval: 5s
      retries: 100

  database:
    image: mongo
    volumes:
      - ~/data/docker-ts:/data/db
    ports:
      - "27010:27017"
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  frontend-deps:
  backend-deps:
